
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: demo
    password: 123456
    url: jdbc:mysql://47.99.143.98:3306/demo?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
server:
  port: 8080
